### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by garygreen** [msurguy/Honeypot#27]
Time for a new release tag? :-)

**Comment by msurguy** [comment]
Yes! Should it be a minor or major ?

**Comment by garygreen** [comment]
I'd just go 0.3.0 personally

**Comment by msurguy** [comment]
@garygreen done! 

 Thanks for all your PRs!

Could you please take a quick look at the readme file and update it if anything is out of sync with your new implementation?

**Comment by garygreen** [comment]
Done in pr #28
