### ISSUE TITLE
Laravel 5 Release

### ISSUE THREAD

**Issue by rbruhn** [msurguy/Honeypot#32]
Is there a release for Laravel 5 yet? I'm trying to upgrade and just using the normal install on the ReadMe causes an error due to HTLM being deprecated.

PHP Fatal error:  Class 'Illuminate\Html\FormBuilder' not found in /vagrant/biospex/vendor/msurguy/honeypot/src/Msurguy/Honeypot/HoneypotServiceProvider.php on line 91

**Comment by garygreen** [comment]
Laravel 5 doesn't ship with the Form / HTML builder anymore. You need to include it in your composer.json and `config/app.php`. See the instructions [here under section Form & HTML Helpers](http://laravel.com/docs/5.0/upgrade#upgrade-5.0)

**Comment by rbruhn** [comment]
Sorry, didn't know the error thrown would be fixed with the laravelcollective/html package due to the call it was making. Might be something you'd like to put in the readme.

**Comment by rbruhn** [comment]
Was still getting the same issue after installing laravelcollective/html.
The problem arises from HoneypotServiceProvider.php and the "use Illuminate\Html\FormBuilder;"
It should be use Collective\Html\FormBuilder;

**Comment by garygreen** [comment]
Hmm, interesting. Laravel 5 is promoting the use of the Collective FormBuilder as well. I supose in the service provider there's not really any need to typecast the form builder. It should then work with the Collective one. Will do a PR

**Comment by rbruhn** [comment]
Sounds great. I will close this issue. Thanks.
