### ISSUE TITLE
FatalErrorException in ProviderRepository.php line 150:

### ISSUE THREAD

**Issue by amatz5** [msurguy/Honeypot#38]
Honeypot is working fine in my localhost using windows

but after i upload my update in my server "Linux"

1. composer.json
2. vendor/msurguy/ all files

Then when i access my website i have the error below:
FatalErrorException in ProviderRepository.php line 150:
Class 'Msurguy\Honeypot\HoneypotServiceProvider' not found

Thanks
In advanced

**Comment by garygreen** [comment]
Have you tried `php artisan clear-compiled` and also `composer dumpautoload` ?

**Comment by amatz5** [comment]
I dont have root access in my server so i install composer locally,

itry php composer.phar clear-compiled

Command "clear-compiled" is not defined

--
but when i try php composer.phar update
is all working now


thanks for you time

**Comment by msurguy** [comment]
@amatz5 glad it's working! can we close this issue now?

**Comment by amatz5** [comment]
yes the issue was close thanks

**Comment by vigneshmuthukrishnan** [comment]
HI FRIENDS 
i have some error on pagination so pls help for me...
blow my error
-------------------------------------------------------
[Symfony\Component\Debug\Exception\FatalErrorException]
Cannot instantiate interface Illuminate\Contracts\Pagination\Paginator

thank u all....
