### ISSUE TITLE
Add the Validation to where ?

### ISSUE THREAD

**Issue by MajdMaghamez** [msurguy/Honeypot#43]
I followed the steps up until adding the honeyPot to the markup pages or in other words ('view')
but i don't understand where you add the validation to the HoneyPot ? 
Do you add it to the controller ? or you add it to the route ? can you please explain.
I am doing a demo so after i ran artisan make:auth on a clean installation of Laravel 5.2.41 I added honey pot the main registration form.
So i am thinking to add it to App\Http\Controllers\Auth\AuthController.php since the validator is already being used in that class.
but i am not sure if thats the right way ? because i wanna also check the time of form being filled too.
can someone please advise.

thanks

**Comment by ITwrx** [comment]
yes, in controller's rules array:

`'my_name'   => 'honeypot',`

`'my_time'   => 'required|honeytime:7',`
