### ISSUE TITLE
Duplicate Id when using the same Honeypot

### ISSUE THREAD

**Issue by Benjyclay** [msurguy/Honeypot#50]
I have two of exactly the same forms on a page, which both include the same `Honeypot::generate()` method. When doing an HTML validity check ([https://validator.w3.org](https://validator.w3.org)) It says there are duplicate ids on the containing div `..._wrap`.

1. Is this wrapper necessary?
2. Is there a way around using the same id on this element

**Comment by mariopro** [comment]
I've noticed the same issue in a multiple forms modal where I had three forms. The solution that I tested and works is to change the `id=""` to `class=""`. This way the honeypot works as supposed and the HTML validation passes.

**Comment by msurguy** [comment]
@Benjyclay @mariopro this is fixed in the newest version of the package. Thanks for your reports!
